services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ./.docker/start.sh
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/myapp?schema=public

  postgres:
    image: bitnami/postgresql:16
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
